[Unit]
# Replace the example Flatpak Bridge dependency when the native Bridge package
# provides protonmail-bridge.service.
After=
After=network-online.target protonmail-bridge.service
Wants=
Wants=network-online.target protonmail-bridge.service
